[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd matrixjupiter && npm ci"]

[phases.build]
cmds = ["cd matrixjupiter && npm run build"]

[start]
cmd = "cd matrixjupiter && npm start"
