[phases.setup]
nixPkgs = ["nodejs-22_x"]

[phases.install]
cmds = ["cd matrixjupiter && npm install"]

[phases.build]
cmds = ["cd matrixjupiter && npm run build"]

[start]
cmd = "cd matrixjupiter && npm start"
